### ISSUE TITLE
Invite / Roster freezes character movement

### ISSUE THREAD

**Issue by KavanBahrami** [oculus-samples/Unreal-SharedSpaces#3] opened 2022-01-06 00:52 UTC
When I land on the Roster Panel or Invite Panel the character's movement is locked. When I click out of the oculus pop-up I am still locked in place. Buttons (jump etc) work and on landing the pop-up comes up again, but unless I quit and restart the game I am unable to move off of the panel base. 

@els-oculus 
Not sure if this is just me. I'll mess with it some more. Just excited overall that it's working!

**Comment by els-oculus** [comment] 2022-01-06 17:58
Yes, that's actually an interesting problem: when the Oculus system dialog pops up, Unreal loses input control, which means that if you are in movement when the dialog pops up (shortly after being requested) you continue moving without being able to stop.  :)

To work around that problem, there is logic that waits for you to stop moving on the pressure plate before locking input UE4-side, THEN send the request to open the system dialog.  I'll review that now.

**Comment by els-oculus** [comment] 2022-01-06 22:28
![character_input](https://user-images.githubusercontent.com/61444568/148461035-fc468cbe-1fdc-4851-b01c-d9fbe8949e94.png)

As a sanity check, could you open the blueprint Content > SharedSpaces > Blueprints > RosterPanelLaunchTrigger
and verify that it does reenable character input on response to launching the roster panel?

**Comment by KavanBahrami** [comment] 2022-01-06 22:50
That code is there.

I added two LogMessage nodes to test on my end, 1 before the GroupPresenceLaunchPanel node and 1 after EnableCharacterInput. The first fires to the board, but the second doesn't.

The messages I get are: 
038> [my message before GroupPresence node]
039> Launching roster panel with 0 user suggestions.
040> Livestreaming status change: comments...

![com oculus sho SharedSpaces-20220106-144558](https://user-images.githubusercontent.com/1649393/148463125-8361a0e8-e924-466e-9799-50b9b6583d84.jpg)

![Screenshot 2022-01-06 14 49 55](https://user-images.githubusercontent.com/1649393/148463386-cf36e7f5-f804-4cb7-bb6d-dd9500187ec8.png)

**Comment by bidonjour** [comment] 2022-01-08 18:49
I got the issue with both Invite Panel and Roaster panel. I also notice that the invite is actually never sent to the other headset. 
I've added some log in the C++ UOculusPlatformSubsystem::GroupPresenceLaunchInvitePanel() method, and I notice that the callback that should be called when closing the invite panel is never called. See the comment below

```
void UOculusPlatformSubsystem::GroupPresenceLaunchInvitePanel(
	const TArray<FOculusId>& SuggestedUsers,
	const FOculusPlatformOnGroupPresenceInvitePanelComplete& Callback)
{
	UE_LOG(LogOculusPlatform, Verbose, TEXT("UOculusPlatformSubsystem::GroupPresenceLaunchInvitePanel"));

	ovrInviteOptionsHandle InviteOptions = ovr_InviteOptions_Create();

	for (int32 UserIndex = 0, TotalUsers = SuggestedUsers.Num(); UserIndex < TotalUsers; ++UserIndex)
	{
		ovr_InviteOptions_AddSuggestedUser(InviteOptions, SuggestedUsers[UserIndex]);
	}

	LogEntry(TEXT("Launching invite panel."));

	AddRequestDelegate(ovr_GroupPresence_LaunchInvitePanel(InviteOptions), FOculusPlatformMessageOnComplete::CreateLambda(
		[this, Callback](ovrMessageHandle Message, bool bIsError)
		{
			// CODE HERE IS NEVER EXECUTED
			bool bInvitesHaveBeenSent = false;

			if (bIsError)
			{
				ovrErrorHandle Error = ovr_Message_GetError(Message);
				FString ErrorMessage(ovr_Error_GetMessage(Error));
				LogError(FString::Printf(TEXT("Error launching group presence invite panel: %s"), *ErrorMessage));
			}
			else
			{
				ovrInvitePanelResultInfoHandle InvitePanelResultInfoHandle = ovr_Message_GetInvitePanelResultInfo(Message);
				bInvitesHaveBeenSent = ovr_InvitePanelResultInfo_GetInvitesSent(InvitePanelResultInfoHandle);

				LogEntry(FString::Printf(TEXT("Group presence invite panel launch complete.  %s sent."), bInvitesHaveBeenSent?TEXT("Invites"):TEXT("No invites")));
			}

			Callback.ExecuteIfBound(!bIsError, bInvitesHaveBeenSent);
		}));

	ovr_InviteOptions_Destroy(InviteOptions);
}
```

The only thing working for me now is when 2 users go in the public purple room. Any other type of connection requiring to use Oculus UI like the invite panel doesn't work unfortunately :( .

Hope it will help you to investigate.

Thanks

**Comment by KavanBahrami** [comment] 2022-01-08 18:53
@bidonjour 's comments here accurately reflect my experience as well. I'm testing with a Q1 and Q2 each with different dev accounts tied to my org with appropriate approvals. The invite doesn't seem to be sent between devices but they will see each other in the purple room.

**Comment by els-oculus** [comment] 2022-01-09 05:00
Please check a few things:
1) that you have enabled, in Data Use Checkup, both "Display friends to invite" and "Enable users to invite others".
2) for testing make sure you send this to a user that is part of your Oculus org.

Regarding movement freezing, this is caused by the servers not sending you back a response.   This is not normal and we will investigate on our end, but a workaround is to not depend on the response.   Here's a visual suggestion:

![workaround](https://user-images.githubusercontent.com/61444568/148670104-1a8b7052-42e5-4278-ac97-ebed113149f5.png)

**Comment by bidonjour** [comment] 2022-01-13 17:42
Hello

In Data Use Checkup everything is enabled form me, and the two accounts are admin members of my Oculus org. Despite this, the invitation is never sent to the other headset.

Thanks

**Comment by KavanBahrami** [comment] 2022-01-14 06:18
@els-oculus Have you looked into calling the StopMovementImmediately node on the character movement component? Then set the MovementMode to None.

Rather than this delay workaround?

**Comment by els-oculus** [comment] 2022-01-19 20:56
@KavanBahrami, I'd like to see your solution to stopping movement immediately.   I'll update the blueprint after testing your solution.  Meanwhile I have checked in the workaround above (using delays) until we fix the callback not being called after the system panel is closed.

@bidonjour, you have a different issue with the invite not being received by the other player.   Please open a separate issue for that, so that we can track that separately from movement issues.

**Comment by nntraining** [comment] 2022-01-19 22:38
@els-oculus, I don't have an implementation, but it's used in the official [Unreal Learning Kit](https://www.unrealengine.com/marketplace/en-US/product/unreal-learning-kit-games) Player Character. I've attached two screenshots here that show it being called and how they use it.

![Screenshot 2022-01-19 14 32 45](https://user-images.githubusercontent.com/97923839/150229774-83bda759-42f6-41d2-91ae-c54941c7e81a.png)
![Screenshot 2022-01-19 14 33 30](https://user-images.githubusercontent.com/97923839/150229780-332ec347-4429-4819-a4bc-ad2ddbc567a9.png)

**Comment by KavanBahrami** [comment] 2022-01-19 22:39
@els-oculus, I don't have an implementation, but it's used in the official [Unreal Learning Kit](https://www.unrealengine.com/marketplace/en-US/product/unreal-learning-kit-games) Player Character. I've attached two screenshots here that show it being called and how they use it.

![Screenshot 2022-01-19 14 32 45](https://user-images.githubusercontent.com/97923839/150229774-83bda759-42f6-41d2-91ae-c54941c7e81a.png)
![Screenshot 2022-01-19 14 33 30](https://user-images.githubusercontent.com/97923839/150229780-332ec347-4429-4819-a4bc-ad2ddbc567a9.png)

**Comment by els-oculus** [comment] 2022-01-20 02:10
Thanks for the examples, @KavanBahrami!

I will recapitulate the issues raised here:
1) When a system dialog pops up (e.g. roster or invite panel), the player loses control of his character as all input is captured by the system.  This is a problem when the dialog pops up while the character is moving, since we can no longer signal to UE4 that we have stopped moving.  The dialog is up, the character keeps moving, and there is nothing that the player can do.
2) To prevent having the dialog pop up in that situation, we first wait for the character to stop moving on the pressure plate.  When that happens, we disable character input temporarily and request the roster/invite panel.
3a) The original implementation then reenabled character input when the panel is closed, which is supposed to send us a response.

ISSUE: Normally that would work, except that there is an issue where that callback is never received.  Since reenabling input depends on this, we end up with the character frozen in place.

The fix: we are fixing the Oculus service to return the response in all cases.
Meanwhile we have implemented a workaround:

3b) Instead of waiting for the callback that currently may never come (due to an Oculus bug), we just wait *enough time for the panel to appear and steal input from UE4*, before reenabling character input.  The character will still not be able to move as long as the dialog is up (since the system steals input from UE4), but as soon as the dialog goes away, the player will have control again, even if the response is not sent by the Oculus service.


As @KavanBahrami mentioned, there are ways to stop the character from moving immediately as soon as you touch the pressure plate.  In SharedSpaces we have (by design) opted for as solution that requires you to stop on the pressure plate to trigger it.   This allows you to run around, go over the plate and continue running without triggering the panel if that was not your intention.

**Closed by els-oculus** 2022-01-20 02:10 UTC
